### ISSUE TITLE
Exporting org ID property as reference to headline

### ISSUE THREAD

**Issue by SidharthArya** [kaushalmodi/ox-hugo#542] opened 2022-01-27 23:54 UTC
Hi,
Is it possible to export org ID as reference to headline and files?

For example:
```
:PROPERTIES:
:ID: 123
:END:

* Hello
  :PROPERTIES:
  :ID: 321
  :END:
```
In the hugo static site, i would like the address of the Hello headline to be /123#321.
Is this possible currently ?

**Comment by kaushalmodi** [comment] 2022-01-28 00:24
Hi Sidharth,

I have some Org id based referencing tests. What have you tried so far? What gets exported and what did you expect instead?

Please provide a complete Org file example that shows the issue.

**Comment by kaushalmodi** [comment] 2022-01-28 00:29
> :PROPERTIES:
> :ID: 123
> :END:

> headline to be /123

That's not supported at the moment. What is the use case for that?

**Comment by kaushalmodi** [comment] 2022-01-28 02:34
> #321

To use the ID as anchor, add this to your emacs config (**untested**):

```el
(defun my/org-hugo--get-anchor(element info &optional title-str)
  "Return an Org heading's anchor.

The anchor is derived in the following precedence:

1. `:CUSTOM_ID' property of the ELEMENT if set
2. `:ID' property of the ELEMENT if set
3. Optional TITLE-STR string argument to this function
4. `:title' property of the ELEMENT

INFO is a plist used as a communication channel.

If the anchor cannot be derived from any of the above, return
nil."
  (or (org-element-property :CUSTOM_ID element)
      (org-element-property :ID element)
      (let ((title (or (org-string-nw-p title-str)
                       (and (org-string-nw-p (org-element-property :title element))
                            (org-export-data-with-backend
                             (org-element-property :title element) 'md info)))))
        (when title
          (org-hugo-slug title :allow-double-hyphens)))))

(with-eval-after-load 'ox-hugo
  (advice-add 'org-hugo--get-anchor :override #'my/org-hugo--get-anchor))
```

Above code, replaces the default `org-hugo--get-anchor` with this custom version where the ID property if set gets precedence over the `:title` property of the element (i.e. the Org heading string).

As the ID is typically not human-readable and deriving a slug out of a subheading title is, I cannot make this change in `ox-hugo`. See if the above works for you.

**Comment by kaushalmodi** [comment] 2022-01-28 05:25
@SidharthArya 

> :PROPERTIES:
> :ID: 123
> :END:

> headline to be /123

This is not exactly what you asked, but something similar is possible. See the description in this PR: https://github.com/kaushalmodi/ox-hugo/pull/543 and also how the test files got updated to get an idea.

**Comment by kaushalmodi** [comment] 2022-01-28 17:13
@SidharthArya 

To use the ID as anchor, add this to your emacs config:

```el
(with-eval-after-load 'ox-hugo
  (setq org-hugo-anchor-functions '(org-hugo-get-custom-id
                                    org-hugo-get-id
                                    org-hugo-get-heading-slug
                                    org-hugo-get-md5)))
```

This feature requires the latest commit from `main` branch of this repo, which should be released in Melpa update of ox-hugo in about an hour.

See the documentation added for this feature at https://ox-hugo.scripter.co/doc/anchors/.

**Comment by kaushalmodi** [comment] 2022-02-03 14:48
I close this issue for now. Please feel free to comment here to discuss this further.

**Comment by SidharthArya** [comment] 2022-02-10 20:52
Just the aliases should be added for various pages. It is not really as much required to have the alases though. I just want to go to the specific web element an org id may link to.

**Comment by kaushalmodi** [comment] 2022-02-10 20:58
> It is not really as much required to have the alases though.

I would then refrain from adding a defcustom for such a case. To keep the package maintainable, I don't want to add corner case defcustoms.

> I just want to go to the specific web element an org id may link to.

As this is already solved, this issue can be closed?

**Comment by SidharthArya** [comment] 2022-02-10 21:02
@kaushalmodi 
The links for the ids are not generated. Would it be possible to have the link to the specific webelement and not just the web page?

**Comment by SidharthArya** [comment] 2022-02-10 21:41
Sure
a.org
```
:PROPERTIES:
:ID:       1fbc4a00-1f40-48d3-a7cf-62f2e89ff486
:END:
#+title: ABC
* Features
+ [[id:48e6dfd4-93d9-4811-855e-c739470e83d1][TSL]]

```
b.org
```
:PROPERTIES:
:ID:       31c61d47-0afc-4d5c-9b60-6c154a1c518d
:END:
#+title: PL

* Features
** TSL
:PROPERTIES:
:ID:       48e6dfd4-93d9-4811-855e-c739470e83d1
:END:
```

**Comment by kaushalmodi** [comment] 2022-02-10 22:07
> Does this work?

Yes, I see that while it uses the org-id for heading anchor, it still uses slug for the heading (derived from an incorrect headline - I will open a separate issue for that) when creating the relref.

## Test Org files

<summary> 

`a.org`
<details>

```org
:PROPERTIES:
:ID:       1fbc4a00-1f40-48d3-a7cf-62f2e89ff486
:END:
#+title: ABC
#+hugo_base_dir: .
#+options: author:nil

* Features
+ [[id:48e6dfd4-93d9-4811-855e-c739470e83d1][TSL]]
```
</details>
</summary>


<summary> 

`b.org`
<details>

```org
:PROPERTIES:
:ID:       31c61d47-0afc-4d5c-9b60-6c154a1c518d
:END:
#+title: PL
#+hugo_base_dir: .
#+options: author:nil

* Features
** TSL
:PROPERTIES:
:ID:       48e6dfd4-93d9-4811-855e-c739470e83d1
:END:
```
</details>
</summary>


<summary> 

`a.md` - Issue here is that it should have created `{{< relref "b.md#48e6dfd4-93d9-4811-855e-c739470e83d1" >}}` instead.
<details>

```md
+++
title = "ABC"
draft = false
+++

## Features {#1fbc4a00-1f40-48d3-a7cf-62f2e89ff486}

-   [TSL]({{< relref "b.md#features" >}})
```
</details>
</summary>


<summary> 

`b.md` - Here the issue is that the ID for TSL got copied to Features as well 
<details>

```md
+++
title = "PL"
draft = false
+++

## Features {#31c61d47-0afc-4d5c-9b60-6c154a1c518d}


### TSL {#31c61d47-0afc-4d5c-9b60-6c154a1c518d}
```
</details>
</summary>

**Comment by SidharthArya** [comment] 2022-02-10 22:24
Yes @kaushalmodi 
Thank you

**Comment by kaushalmodi** [comment] 2022-02-18 04:16
@SidharthArya Can you update `ox-hugo` from main branch and try updating from Melpa in an hour? The issues in https://github.com/kaushalmodi/ox-hugo/issues/542#issuecomment-1035579884 are fixed now I believe.

**Comment by SidharthArya** [comment] 2022-02-20 22:46
Hi @kaushalmodi
It's working.

**Comment by kaushalmodi** [comment] 2022-02-20 23:23
Thanks. I'm closing this issue.

**Closed by kaushalmodi** 2022-02-20 23:23 UTC
Labels: awaiting user response, org-id
