### ISSUE TITLE
static file links are not correctly exported from org to the md files.

### ISSUE THREAD

**Issue by dominikpegler** [kaushalmodi/ox-hugo#438] opened 2021-04-07 10:45 UTC
Hi, this is a great package. I am on Emacs 26.3 and ox-hugo version 20210330.1758 and I have the following issue:

**Static file links are not correctly exported from org to md.**

I have this link in the org file and export it with C-c C-e H H

 `[[file:./this_image.jpg]]`

and I always get this in the markdown file:

`{{< figure src="/./this_image.jpg" >}}`

The problem with this sequence (`/./` instead of just `./`) is, that it ignores the baseURL. E.g. the page is sitting at `myusername.github.io/blog  `, but the link points to `myusername.github.io/this_image.jpg` instead of `myusername.github.io/blog/this_image.jpg`.

**Comment by kaushalmodi** [comment] 2021-04-07 11:55
> it ignores the baseURL.

Hello, that's a Hugo issue. Hugo doesn't do the right thing when the baseURL has a subdirectory. I had analyzed that problem few years back. The fix was to use a custom figure shortcode: https://github.com/gohugoio/hugo/issues/4562#issuecomment-378314838

**Comment by kaushalmodi** [comment] 2021-04-07 12:00
Also check out the documentation on exporting images here: https://ox-hugo.scripter.co/doc/image-links/

You don't need the `./`. Once you fix the figure shortcode, the image exports will work as intended.

**Comment by dominikpegler** [comment] 2021-04-07 12:41
Thank you for such a quick response.

So the problem is not the `"/./"` in the markdown file but how Hugo is handling it?

**Comment by kaushalmodi** [comment] 2021-04-07 12:48
Remove the `./` and even then Hugo should have used the baseURL with the subdir. 

Good thing is that it's easily fixed by placing that custom figure shortcode definition in your theme.

**Comment by dominikpegler** [comment] 2021-04-08 06:59
Thank you! This solved it for me

**Closed** 2021-04-08 13:37 UTC
Labels: bug, upstream
