### ISSUE TITLE
Indentation in Python code blocks not preserved

### ISSUE THREAD

**Issue by amca01** [kaushalmodi/ox-hugo#314] opened 2019-12-19 12:49 UTC
Hello,

I often include code blocks in my posts, such as:

    #+BEGIN_SRC python
    import itertools as it
    import numpy as np
    
    def permanent(m):
        nr,nc = np.shape(m)
        if nr != nc:
            raise ValueError("Matrix must be square")
        pm = 0
        for p in it.permutations(range(nr)):
            pm += np.product([m[i,p[i]] for i in range(nr)])
       return pm
    #+END_SRC

The only trouble is that after being exported and run through hugo, only one layer of indentation is preserved; on the blog itself I get

    import itertools as it
    import numpy as np
    
    def permanent(m):
        nr,nc = np.shape(m)
        if nr != nc:
        raise ValueError("Matrix must be square")
        pm = 0
        for p in it.permutations(range(nr)):
        pm += np.product([m[i,p[i]] for i in range(nr)])
       return pm

My base `config.toml` contains:

    pygmentsUseClassic = false
    pygmentsCodeFences = true
    pygmentsStyle = "perldoc"

and the first of these lines can be removed with no change (I can't now remember why I put it there).  How can I force (ox-)hugo to maintain my indentation - or do I have to start putting in hard spaces somehow?   Thank you!

By the way, if this is the wrong place for this, I'd be happy to be told where the right place is to ask such a question.  But as my entire involvement with Hugo is through ox-hugo, I always assume that wiser heads than mine inhabit this forum.

**Comment by kaushalmodi** [comment] 2019-12-19 12:53
Hello, that indeed is an odd behavior. 

Can you share the Org source and the entire ox-hugo generated Markdown with this code block? (Probably a link to those?)

**Comment by amca01** [comment] 2019-12-19 13:01
Thank you for your quick reply!  The org source is what I posted initially; everything between `#+BEGIN_SRC` and `#+END_SRC`

In fact I just checked the Hugo-generated Markdown, and that's where the indentation disappears; the Markdown source contains:

    ```python
    import itertools as it
    import numpy as np
    
    def permanent(m):
        nr,nc = np.shape(m)
        if nr != nc:
        raise ValueError("Matrix must be square")
        pm = 0
        for p in it.permutations(range(nr)):
        pm += np.product([m[i,p[i]] for i in range(nr)])
        return pm
```
If I now put the indentation back in manually, all is well.  But this would be a bit of a pain to do on a regular basis.  

Maybe I'm including code incorrectly: is there an alternative to `#+BEGIN_SRC` and `#+END_SRC`?  Thank you again.

**Comment by kaushalmodi** [comment] 2019-12-19 13:33
Hello,

I am unable to reproduce that issue. See

![image](https://user-images.githubusercontent.com/3578197/71177467-1391ef00-223a-11ea-95fa-5657093e09fe.png)

I would guess that you would see the same issue in any Org exporter.. try exporting to HTML using ox-html as an example  (`C-c C-e h h`).

My guess would be that you have something in your emacs config that's doing this.

**Comment by kaushalmodi** [comment] 2019-12-19 13:38
@amca01 To debug this, I would suggest that you first comment out all of your emacs config except for the part that loads `ox-hugo`, and then restart emacs. This issue should stop happening once you do that.

Then incrementally uncomment your config until to find the culprit.

**Comment by kaushalmodi** [comment] 2019-12-19 13:54
@amca01 I have updated a source block export test to show that the python code exports with all the indentations correct: https://ox-hugo.scripter.co/test/posts/code-fenced-src-blocks-default/.

**Comment by amca01** [comment] 2019-12-19 22:07
Thanks very much - I'll do as you suggest with my `.emacs`.  It is very long however (336 lines) so this might be a slow process!

**Comment by kaushalmodi** [comment] 2019-12-19 22:53
@amca01 Try using spaces for indentation instead of tabs may be? 

ox-hugo does not deal with tab/space conversion. 

>  It is very long however (336 lines) so this might be a slow process!

Use the "binary approach". Comment the whole file, test it out, when uncomment half of the file, test it, and so on ..

By using the binary uncommenting approach, you will find out the issue pretty soon.

**Comment by kaushalmodi** [comment] 2019-12-19 22:54
>  I don't know whether this is an ox-hugo or an org-hugo thing!

Do you see the same problem when you export to HTML using `ox-html` (try `C-c C-e h h`)?

**Comment by amca01** [comment] 2019-12-20 00:04
Ahh - export to html does it perfectly!

**Comment by kaushalmodi** [comment] 2019-12-20 01:13
@amca01 Can you commit your source Org file somewhere for me to see, so that I can get the exact tab/space characters. I need to be able to reproduce the issue to fix it.

**Comment by amca01** [comment] 2019-12-20 05:39
Thank you very much - I'll do that a bit later: and then let you know when it's been done.

**Comment by amca01** [comment] 2019-12-21 00:25
You can find all my blog post info at 

https://github.com/amca01/whats_this 

Note that the org file is automatically rendered properly by github!

(This took me a while because I only make a commit rarely, and every time I seem to have to re-learn git from scratch.  It's still mostly a mystery to me...)

**Comment by amca01** [comment] 2019-12-23 11:21
For what it's worth, a workaround is to double the spaces, so that a 4 space indent is made by putting 8 spaces in the initial org file.  I don't know why this works, but at least it does!  See my [latest blog post](https://numbersandshapes.net/post/permanents_and_rysers_algorithm/) for some examples of source code.

**Comment by yamada-github-account** [comment] 2020-02-05 20:38
Hi,

I had a same problem, too.

I uses GitLab CI/CD.
The configuration is simple, and helps you hopefully.

*  [org file](https://gitlab.com/ymd_h/ymd_blog/-/blob/28e3e21689d802218ef23ea407984df7a3d4450a/blog.org#L2708)
*  [Exporting command at CI](https://gitlab.com/ymd_h/ymd_blog/-/blob/28e3e21689d802218ef23ea407984df7a3d4450a/.gitlab-ci.yml#L14)
*  [emacs config](https://gitlab.com/ymd_h/ymd_blog/-/blob/28e3e21689d802218ef23ea407984df7a3d4450a/init.el)
* [output markdown](https://gitlab.com/ymd_h/ymd_blog/-/jobs/426748535/artifacts/file/content/posts/setup_config_for_cython_numpy/index.md)
* [output HTML](https://ymd_h.gitlab.io/-/ymd_blog/-/jobs/426748537/artifacts/public/posts/setup_config_for_cython_numpy/index.html)

---

It seems every 8 spaces is replaced by a single TAB.
*  4 spaces -> 4 spaces
*  8 spaces -> 1 TAB
*  17 spaces -> 2 TAB + 1 space


I assume disabling this TAB replacement will fix this problem. 
(Sorry, I couldn't find where, and probably outside ox-hugo?)

**Comment by yamada-github-account** [comment] 2020-02-06 12:06
OK, I found fix by myself.

I didn't know `org-src-preserve-indentation` do the job for the org-export as well as for editing buffer.
[How to indent without the two extra spaces at the beginning of code blocks in org mode?](https://emacs.stackexchange.com/questions/18877/how-to-indent-without-the-two-extra-spaces-at-the-beginning-of-code-blocks-in-or/18892#18892)

* [diff](https://gitlab.com/ymd_h/ymd_blog/-/compare/28e3e21689d802218ef23ea407984df7a3d4450a...ed4bf1fc29cb361cb1794fe010bca2bfbf618fca)
* [markdown](https://gitlab.com/ymd_h/ymd_blog/-/jobs/428041677/artifacts/browse/content/posts/setup_config_for_cython_numpy/)
* [html](https://ymd_h.gitlab.io/-/ymd_blog/-/jobs/428041678/artifacts/public/posts/setup_config_for_cython_numpy/index.html)

**Comment by kaushalmodi** [comment] 2020-04-27 14:53
@yamada-github-account I appreciate your response!

@amca01 Unfortunately, I was never able to reproduce the issue you are seeing. I will assume that changing the above variable in your Emacs config would help resolve this issue for you. So I am closing this today.

**Closed by kaushalmodi** 2020-04-27 14:53 UTC
