### ISSUE TITLE
Support org-mode option for svg and png math formatting

### ISSUE THREAD

**Issue by rayes0** [kaushalmodi/ox-hugo#473] opened 2021-11-26 22:03 UTC
In addition to using MathJax, org can also [format math as images and insert them as html](https://orgmode.org/manual/Math-formatting-in-HTML-export.html). However, when using this with ox-hugo, the images aren't copied to the Hugo static directory. For example:

```tex
#+options: tex:dvisvgm

The equation for the Archimedian spiral is $y\cos(\sqrt{x^2 + y^2}) = x\sin(\sqrt{x^2 + y^2})$.
```

When exported with ox-hugo becomes:

```md
The equation for the Archimedian spiral is <img src="ltximg/blog_e072a7104f1c6edbf1ee81ad0a05e7ef2186cdb0.svg" alt="$y\cos(\sqrt{x^2 + y^2}) = x\sin(\sqrt{x^2 + y^2})$" class="org-svg" />.
```

The reference is still pointing to the ltximg directory relative to the org file. It would be ideal if the image would be copied to the Hugo static directory and linked to there. Doing this would allow users to use static images instead of MathJax. The use case would be, for example if I have a page with only one or two simple tex formulas (such as $x$ or something) I wouldn't want to load all the overhead of MathJax JS + all it's CSS rules + all the custom fonts it brings in just for those one or two formulas.

**Comment by kaushalmodi** [comment] 2021-11-26 22:59
Does it help if you set the `org-preview-latex-image-directory` to an ltximg dir path pointing in your Hugo static dir?

You might even set that var in the .dir-locals.el in the directory holding your site's Org source.

**Comment by rayes0** [comment] 2021-11-27 19:34
It works for moving where the image is generated, however because the paths are still relative paths from where the Org file is (or an absolute path from the filesystem root), they are still messed up. The only way to make it work would be to have the Org file be in the same directory (or the same directory level) as the generated markdown files. The problem with this is that it gets messed up when using subtree based export to multiple different directory levels from a single Org file.

I did manage to find a rather convulsed way to fix this. I'll leave it here for anyone who comes across this. I skimmed ox-hugo's code, and it seems ultimately to use `org-format-latex` in org.el (`org-html-latex-environment`, `org-html-latex-fragment`, and `org-html-format-latex` all appear to call `org-format-latex` in the backend).

While looking through org.el, I noticed an (undocumented?) feature, where if `tex:html` is set, it will use a custom command defined in the variable `org-latex-to-html-convert-command`.

I wrote a quick shell script that converts tex fragments -> xdv with xelatex, and then from xdv -> svg in the Hugo static dir with dvisvg. It then echos some an html reference to the svg to be inserted into the markdown. Another probably easier way would be to install MathJax via npm or something and use it's provided `tex2svg`.

orgltx.sh:
```bash
#!/bin/bash

svgfile="$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 32).svg"
orgsvg="/home/rayes/sites/blog/static/orgltx/${svgfile}"
mkdir -p "~/sites/blog/static/orgltx" >/dev/null 2>&1

echo -e "\\documentclass{standalone}\n\\begin{document}\n\\($1\\)\n\\end{document}" > /tmp/orgltx.tex
xelatex -no-pdf -interaction nonstopmode -output-directory '/tmp/' /tmp/orgltx.tex >/dev/null 2>&1
dvisvgm --stdout /tmp/orgltx.xdv 2>/dev/null > ${orgsvg}
echo "<img src=\"/orgltx/${svgfile}\" alt=\"$1\" class=\"org-svg\">"
```

Then in emacs, I set the variable to use the script: `(setq org-latex-to-html-convert-command "orgltx.sh '%i'")`. Unfortunately, this only works when it's globally set so setting it in .dir-locals.el won't work.

In the org file:
```tex
#+options: tex:html

The equation for the Archimedian spiral is $y\cos(\sqrt{x^2 + y^2}) = x\sin(\sqrt{x^2 + y^2})$.
```

Now when exported to md gives a correct reference to the static dir:

```md
The equation for the Archimedian spiral is <img src="/orgltx/16QCadkcPb4d7rOr56xhapY1tcSyjwAl.svg" alt="$y\cos(\sqrt{x^2 + y^2}) = x\sin(\sqrt{x^2 + y^2})$" class="org-svg".
```

**Comment by kaushalmodi** [comment] 2022-01-05 06:51
@rayes0 Upon looking closely, this is a duplicate of https://github.com/kaushalmodi/ox-hugo/issues/327 and this feature got implemented recently. Please update to the latest commit of ox-hugo and try again.

- Test case: https://ox-hugo.scripter.co/test/posts/equations-exported-to-svg/
  - [Markdown source of that test](https://raw.githubusercontent.com/kaushalmodi/ox-hugo/main/test/site/content/posts/equations-exported-to-svg.md)

Granted that I have tested this only with `dvisvgm`. It probably doesn't support PNG export.

In any case, let me know if this update works for you.

**Closed** 2022-01-06 16:54 UTC
Labels: awaiting user response, duplicate

**Comment by kaushalmodi** [comment] 2022-01-06 16:56
Closed this ticket after adding a test for `dvipng` as well. I have confirmed that both `dvisvgm` and `dvipng` based equation exports work well, and the images get copied over to static/.

**Comment by rayes0** [comment] 2022-01-06 21:48
@kaushalmodi Thanks for letting me know! It works as expected :)
