### ISSUE TITLE
Support :target attribute for #+toc keyword

### ISSUE THREAD

**Issue by asthagiri** [kaushalmodi/ox-hugo#393] opened 2020-09-08 21:17 UTC
## Actual Behavior
To place a TOC at a specific location, I inserted: `#+toc: headlines 3 :target #reading-material`

It produces the expected behavior when I use `org-export` to produce HTML. 

However, when I use `ox-hugo`, the Message buffer shows the following error when it reaches the subtree containing the `#+toc: ....` statement:
`org-hugo-keyword: Wrong type argument: char-or-string-p, nil`

## How to Reproduce the Issue

Below is a simplified version of the org file:

```
* Reading
:PROPERTIES:
:EXPORT_HUGO_SECTION: reading
:EXPORT_OPTIONS: toc:3 num:3
:CUSTOM_ID: reading-material
:END:

** landing page
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_TITLE: blah blah
:HUGO_MENU: :menu main
:END:

#+toc: headlines 3 :target #reading-material

** first subsection in Reading
:PROPERTIES:
:CUSTOM_ID: asdfasdf
:EXPORT_FILE_NAME: asdfasdf
:END:

```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment] 2020-09-11 03:53
Hello, I will review how ox-html supports the [`:target` attribute][1] and attempt to port it to ox-hugo.

[1]: https://orgmode.org/manual/Table-of-Contents.html

**Comment by kaushalmodi** [comment] 2020-09-11 04:57
Hello, the issue is auto-closed as I linked it to the commit implementing this feature. But feel free to comment here if the TOC :target is not working for you.

You can find the ox-hugo test added for this feature in https://github.com/kaushalmodi/ox-hugo/commit/082f229fb18881614a0de60bbd096aac9cbb427f, and the Hugo rendered output of that test is on https://ox-hugo.scripter.co/test/posts/toc-target/ .

**Comment by asthagiri** [comment] 2020-09-17 14:09
Strangely, still not working on my end. I updated my ox-hugo installation to version 20200911.453 through MELPA.

**Comment by kaushalmodi** [comment] 2020-09-17 15:08
>still not working on my end

ox-hugo test suite is passing. So it's certainly working in the remote environment on Travis CI. Unfortunately I cannot help fix this if I cannot reproduce the issue locally.

I will leave this issue open until you have figured it out.

**Comment by asthagiri** [comment] 2020-09-18 22:52
Still working on troubleshooting... the error I get now is different from the OP. Now, the error is:

`user-error: Unable to resolve link: "targetname"`

Strangely, it still works fine on regular org-export to HTML.

**Comment by kaushalmodi** [comment] 2022-01-01 07:08
Hello,

Sorry for the late reply, but I just found some time to look into this.

The reason your example won't export is that you are trying to inject the toc from a different export scope (different post subtree) into the current export scope.

You have:

```org
** Chapter Two
:PROPERTIES:
:CUSTOM_ID: chapter-2
:EXPORT_FILE_NAME: chapter2
:EXPORT_HUGO_MENU: :menu 
:EXPORT_HUGO_PUBLISHDATE: 2020-09-17
:END:

#+toc: headlines 3 :target #chapter-1
```

When I try to export the "chapter-2" post, I see this error, which I expect:

> org-export-data: Unable to resolve link: "chapter-1"

It's because the Org exporter "looks" only within the scope of that subtree and it's unable to find the `#chapter-1` reference -- it's present in outside the current export scope.


> Strangely, it still works fine on regular org-export to HTML.

You will get the same error with HTML export as well. Try putting the point somewhere in the `** Chapter Two` subtree, like on the `#+toc: headlines 3 :target #chapter-1` line and do `C-c C-e C-s h o`. The `C-s` will do a subtree-scope export just as ox-hugo does. And you will see the same error

---

**What does this mean?**

It's a limitation of the Org exporter and we cannot export one subtree which has references outside the scope of that. So this request cannot be supported by ox-hugo.

You should be able to work this out using a custom Hugo shortcode or page template though. You can call a shortcode to inject a TOC from a different page (chapter 1 in your example). Reach out on the Hugo Discourse forum for help on this.

I'll close this issue as the basic toc :target feature works when the target is in the current export scope. While the issue is closed, you can still comment and we can continue the discussion if you are still interested in this.

**Closed by kaushalmodi** 2022-01-01 07:08 UTC
Labels: wontfix, not-a-bug
