### ISSUE TITLE
org-id parse error filename

### ISSUE THREAD

**Issue by GTrunSec** [kaushalmodi/ox-hugo#395] opened 2020-09-19 06:42 UTC
## Actual Behavior
using `org-id-store-link` and `org-id-copy` to creates or inserts org-id point.
- EXAMPLE:
```
:PROPERTIES:
:ID:       3e3b70a4-a6de-4074-bb41-7c781b0fdfa3
:END:
```
- source  block
 [[id:3e3b70a4-a6de-4074-bb41-7c781b0fdfa3[HEADLINE]]

- the ox-hugo-export will be parsed the `source block id` to
  `FIENAME.md` that full output is `[HEADLINE](FILENAME.md)`
## Expected Behavior
parses `FILENAME.md` to `  [HEADLINE]({{< relref "FILENAME.md" >}})` 
same like parsing file link process such as `- [[file:FILENAME.org::*HEADLINE][HEADLINENAME]` to `[HEADLINE]({{< relref "FILENAME" >}})`

**Comment by GTrunSec** [comment] 2020-09-19 21:50
@kaushalmodi  I think,  this parsing way can be fixed the `org-id` problem.  Thanks if you have time to fix it.

**Comment by GTrunSec** [comment] 2020-09-22 02:55
@kaushalmodi Sorry disturb to you. May this [doc link](https://gohugo.io/content-management/cross-references/) help you understand the reference query syntax.
Also, the permalink to a heading is important for us.
```
[org-HEADLINE]({{< relref "FILENAME#Md-HEADLINE" >}})
```
this my solution: first using org-element-property :ID via org-element to get headline value.
then, parsing the headline to Markdown-heading format such as :
```
heading: [[https://github.com/mitmath/18S191][mitmath/18S191: Course 18.S191 at MIT, fall 2020 - Introduction to computational thinking with Julia:]]
ID value is: 3e3b70a4-a6de-4074-bb41-7c781b0fdfa3
markdown-heading: {#mitmath-18s191-course-18-dot-s191-at-mit-fall-2020-introduction-to-computational-thinking-with-julia}
```

**Comment by jethrokuan** [comment] 2020-10-05 18:44
+1 on this, I think generating either a ref or relref shortcode would be great.

**Comment by kaushalmodi** [comment] 2020-10-12 12:54
@GTrunSec @jethrokuan Can one of your please provide a PR?

**Comment by NightMachinary** [comment] 2021-05-17 11:29
@kaushalmodi I noticed that the links `ox-hugo` generates only use the `basename` of the file. I have multiple files with the same name but in different sections, and if we provide the fullpath of the pages to `relref` things will work correctly. 

Bad link:
```
### [{{< relref "anime" >}}]({{< relref "anime" >}})
```

Good links:
```
### [{{< relref "rationalish/anime" >}}]({{< relref "rationalish/anime" >}})

### [{{< relref "posts/bookmarks/watch/rationalish/anime" >}}]({{< relref "posts/bookmarks/watch/rationalish/anime" >}}) {#dot-rationalish-anime-dot-md}
```

---

I am currently using the PR https://github.com/kaushalmodi/ox-hugo/pull/401 ; Should I commit the necessary changes on top of that and send a PR?

I can solve this issue as well; The relevant code seems to be at lines `2075` in `org-hugo-link`. But it seems that `org-hugo-link`'s other parts also need to be fixed to use the correct `relref`, no?

**Comment by NightMachinary** [comment] 2021-05-17 11:32
One problem is fixing the aforementioned problem is that `org-hugo--get-section-path` needs an `info` `plist`, but all we have on hand is a filepath.

**Comment by kaushalmodi** [comment] 2021-05-17 12:25
@NightMachinary 

> I noticed that the links ox-hugo generates only use the basename of the file. 

Yes, that was intended because I hadn't come across a use case like yours. So I am using only the basename:

https://github.com/kaushalmodi/ox-hugo/blob/be7fbd9f164d8937b2628719e21e8e6b4827e638/ox-hugo.el#L2297-L2300

>Should I commit the necessary changes on top of that and send a PR?

Thanks for offering to provide a PR! Can you please rebase to the primary branch of this repo? PR 401 is unrelated to this feature, right?

> But it seems that org-hugo-link's other parts also need to be fixed to use the correct relref, no?

If you have the PR code ready, you can create a PR and we can discuss in that thread. Otherwise, can you briefly describe what your PR will do?

**Comment by NightMachinary** [comment] 2021-05-17 16:31
@kaushalmodi I haven't coded anything yet, but what I have in mind is:


- for normal file path links: call `org-hugo--get-section-path` on the destination of the link then create `{{< relref "section1/section2/file" >}}` links.
- for ID links: do the same

Can you merge that PR? I can't work on the master, as my setup is lots of files with zero hugo-related metadata (I even generate the `_index.md` files with a script), so without that PR, nothing would work for me.

**Comment by kaushalmodi** [comment] 2021-05-18 02:42
@NightMachinary 

> Can you merge that PR?

Done.

**Comment by alexkehayias** [comment] 2021-07-22 01:02
I ran into this now that `org-roam` v2 requires ID links. If I understand correctly, the issue is that ID links will be resolved by `ox-hugo` _without_ a `relref` like it does for file links?

Is this the right place to look for a place to patch so it behaves like file links? https://github.com/kaushalmodi/ox-hugo/blob/be7fbd9f164d8937b2628719e21e8e6b4827e638/ox-hugo.el#L2054

**Comment by kaushalmodi** [comment] 2021-07-22 02:05
Hello @alexkehayias  

Yes, that's the area where this change would happen. 

Would you be willing to work on a PR which also includes few tests related to this change?

**Comment by alexkehayias** [comment] 2021-08-10 03:50
@kaushalmodi can you let me know if this change matches what you were thinking before I submit a PR? This works for me: https://github.com/alexkehayias/ox-hugo/pull/1/files

**Comment by kaushalmodi** [comment] 2021-08-10 12:48
@alexkehayias 

Quickly looking at your PR in your fork, it's creating a separate case statement for "id". Wouldn't that break the existing org-id processing done in https://github.com/kaushalmodi/ox-hugo/blob/6ec3d054ddadbca1f5effb961c1db583e377ca35/ox-hugo.el#L2081-L2089 ?

If you open a PR in this repo, we can see if all the tests are still passing using that code change. Also, please add new tests related to this code change in your PR.

@coldnight I am copying you in this issue as you recently submitted a PR to improve the org-id handling ( https://github.com/kaushalmodi/ox-hugo/pull/453 ). May be you can comment on the change that @alexkehayias is proposing.

**Comment by coldnight** [comment] 2021-08-11 23:20
I'm not sure that is there a `id` link will be a `headline`:
https://github.com/kaushalmodi/ox-hugo/blob/6ec3d054ddadbca1f5effb961c1db583e377ca35/ox-hugo.el#L2090-L2103

If the answer is no, then I think a separate case statement for "id" is okay, need some test case first.

**Comment by kaushalmodi** [comment] 2022-01-05 02:33
From few recent tests added to this repo, I see `relref` links being created properly for org-id references. This issue was created before https://github.com/kaushalmodi/ox-hugo/pull/453.

Closing this for now. If the issue persists, then I didn't understand the actual problem. If so, please provide a minimum example showing the issue and I'll re-open this issue.

**Closed by kaushalmodi** 2022-01-05 02:33 UTC
Labels: org id
