### ISSUE TITLE
problem with pandoc citations

### ISSUE THREAD

**Issue by mclearc** [kaushalmodi/ox-hugo#336] opened 2020-03-10 21:55 UTC
## Actual Behavior

Doesn't convert exported markdown file to one with citations. Message reads "Using the original Ox-hugo output instead of Pandoc output as it contained no References"

## Expected Behavior

Take exported markdown file with '@citations' and convert to formatted citations with pandoc (I'm using latest versions of pandoc and pandoc-citeproc). Note that the pandoc command works when I run it from the command line on the exported markdown file. It just doesn't work as part of the export process using ox-hugo. 

## How to Reproduce the Issue

Just export an org file to markdown using ox-hugo and pandoc

### Example Org File

```org
#+HUGO_BASE_DIR: ..
#+BIBLIOGRAPHY: /Users/roambot/Dropbox/Work/bibfile.bib
#+HUGO_PANDOC_CITATIONS: t
#+HUGO_FRONT_MATTER: :link-citations true
#+hugo_auto_set_lastmod: t
#+OPTIONS: H:2
#+hugo_front_matter_format: yaml
#+HUGO_SECTION: zettels
#+TITLE: Test 1

Pellentesque dapibus suscipit ligula.[fn:1]

And here is a reference @kitcher1975 


[fn:1] Here is another reference [@kitcher1990].  

* References
```

### Generated Markdown File or Error

```md
---
title: "Test 1"
author: ["Colin McLear"]
lastmod: 2020-03-10T17:52:04-04:00
draft: false
---

Pellentesque dapibus suscipit ligula.[^fn:1]

And here is a reference @kitcher1975


## References {#references}

[^fn:1]: Here is another reference [@kitcher1990].
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
     of 2019-09-25

## Org Version

    Org mode version 9.3.6 (9.3.6-23-g01ee25-elpaplus @ /Users/roambot/.emacs.d/.local/elpa/org-plus-contrib-20200309/)

## Hugo Version

    Hugo Static Site Generator v0.67.0/extended darwin/amd64 BuildDate: unknown

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

**Comment by aseltmann** [comment] 2020-03-24 14:44
I can confirm this issue! (I don't know if these kind of posts help, if not, please let me know...)

**Comment by kaushalmodi** [comment] 2020-03-24 21:38
@aseltmann It helps! Thanks. I am still bogged down by work. So I don't have time to look at this (and few other recently collected issues) yet.

**Comment by kaushalmodi** [comment] 2020-04-03 03:04
@mclearc @aseltmann I have merged https://github.com/kaushalmodi/ox-hugo/pull/340. Please verify if that fixes this issue.

**Comment by aseltmann** [comment] 2020-04-03 23:20
Yes, it works for me! Thanks everyone!

**Comment by mclearc** [comment] 2020-04-05 19:46
Hmm - I may have closed this issue prematurely. With the fix ox-hugo correctly exports pandoc citations but it now breaks file links. So now this: `[[file:foo.org][foo]]` gets exported to this: `\[foo\]({{< relref "foo" >}})`. Any idea what could be doing this? Note that other links, such as web links, get processed correctly.

**Comment by kaushalmodi** [comment] 2020-04-06 01:26
> With the fix ox-hugo correctly exports pandoc citations but it now breaks file links. 

Do you think those file link breakages have anything to do with pandoc? Can you verify if you see (or don't) the same issue in a minimal Org example that doesn't use the Pandoc citations?

**Comment by mclearc** [comment] 2020-04-06 02:59
I can verify that a file (any file) that has at least one citation breaks file links. Without any citations the same file is converted fine.

**Comment by kaushalmodi** [comment] 2020-04-06 03:05
In that case, sounds like Pandoc is doing that transformation. Can you check if this regression is caused by a new Pandoc version?

**Comment by mclearc** [comment] 2020-04-06 03:07
I have pandoc 2.9.2.1. Certainly an update to panic caused the problem with citations; perhaps there is a also a related issue with links? It seems like pandoc now makes file links literal rather than working links. I have no idea why, unfortunately.

**Comment by aseltmann** [comment] 2020-04-06 22:34
I had some export problems as well and found *nocite* to be the culprit. Since I just started using ox-hugo, I can not say if the behaviour described below was introduced with the latest fix or if it was there before. Anyway - check this out:

<details>
 <summary>My org-mode test section</summary>

** Critical test section

:PROPERTIES:
:EXPORT_HUGO_SECTION: docs/notes/section
:EXPORT_FILE_NAME: file-name
:END:

*** test section
Test section text.

#+BEGIN_EXPORT html
{{< tabs "uniqueid" >}}
{{< tab "test" >}}

foo[^1]
[^1]: bar

{{< /tab >}}
{{< /tabs >}}
#+END_EXPORT

Some more text
</details>

- - -
Exporting this as it is results in:

<details>
 <summary>Normal export of org-mode test section</summary>

<code>## test section {#test-section}</code>

Test section text.

{{< tabs "uniqueid" >}}
{{< tab "test" >}}

foo[^1]
[^1]: bar

{{< /tab >}}
{{< /tabs >}}
</details>

- - - 
So far, so good (I did not include the hugo frontmatter, since it stayed the same in all exports). Now, we introduce custom front matter to include a nocite reference. The reference which is printed here by nocite was taken from a .bib file I specified at the beginning of the org-file with the bibliography keyword: `#+bibliography: cite/books.bib`.

<details>
 <summary>Broken export - version A</summary>

<code>## test section</code>

Test section text.

{{< tabs "uniqueid" >}} {{< tab "test" >}}

foo\[\^1\] \[\^1\]: bar

{{< /tab >}} {{< /tabs >}}

<code>## References {#references}</code>

<code>< div id="refs" class="references" ></code>
  <code>< div >< /div ></code>


<code>< div id="ref-kapu2002shadow" ></code>
  <code>< div >< /div ></code>

Kapuscinski, Ryszard. 2002. *The Shadow of the Sun*. Random House of
Canada.
[https://books.google.de/books?id=P-R4\\\_z\\\_vsXsC](https://books.google.de/books?id=P-R4\_z\_vsXsC).

<code>< /div></code>

<code>< /div></code>
</details>

- - - 
Notice the missing  `{#test-section}`, the scrambled shortcode,  and the footnotes looking similarly formatted to what @mclearc reported. But now comes the fun part: I did a *tiny* change in the org-file, namely I introduced a line break between the footnote signs in such a way:

```
foo[^1]

[^1]: bar
```

And this changed the export of the footnotes significantly and changed it to org-mode style (notice that it does not change without the nocite frontmatter):

<details>
 <summary>Broken export - version B</summary>

<code>## test section</code>

Test section text.

{{< tabs "uniqueid" >}} {{< tab "test" >}}

<code>foo[^fn:1]</code>

{{< /tab >}} {{< /tabs >}}

<code>## References {#references}</code>

<code>< div id="refs" class="references" ></code>
  <code>< div >< /div ></code>


<code>< div id="ref-kapu2002shadow" ></code>
  <code>< div >< /div ></code>

Kapuscinski, Ryszard. 2002. *The Shadow of the Sun*. Random House of
Canada.
[https://books.google.de/books?id=P-R4\\\_z\\\_vsXsC](https://books.google.de/books?id=P-R4\_z\_vsXsC).

<code>< /div></code>

<code>< /div></code>

<code>[^fn:1]: bar</code>
</details>

**Comment by kaushalmodi** [comment] 2020-04-07 00:09
@aseltmann @mclearc I am afraid that this then means that it's a regression in pandoc. If this issue is not tracked upstream, then may be it should.

Along with that, is there a last stable pandoc version that does not cause the above issue? If so, I can mention that version as the "good version" to be used along with ox-hugo.

**Comment by kaushalmodi** [comment] 2020-04-07 00:14
@HaoZeke The `"-raw_attribute"` option was added in your PR in https://github.com/kaushalmodi/ox-hugo/commit/0cf3965cd498b454012416d7ca262a6728e1b11c. Would that cause this regression in the pandoc-generated output?

**Comment by aseltmann** [comment] 2020-04-14 00:13
@kaushalmodi I just tried to write a MWE of a small .org file, which I would convert to markdown using something like `pandoc -f org -t markdown -o test.md test.org` or `pandoc --filter pandoc-citeproc test.org -s -o test.md` which reproduces the examples I showed above, but it actually failed - I think I am missing insights in how pandoc, hugo and ox-hugo actually work. Could you help? :)

This is how far I've come:
```
#+bibliography: books.bib
#+link-citations: t

* Tests
** Test1 slide
   - This is test1 \cite{kapu2002shadow}.

#+BEGIN_EXPORT html
{{< tabs "uniqueid" >}}
{{< tab "test" >}}

foo[^1]
[^1]: bar

{{< /tab >}}
{{< /tabs >}}
#+END_EXPORT
```

**Comment by kaushalmodi** [comment] 2020-04-17 15:44
> I just tried to write a MWE of a small .org file, which I would convert to markdown using something like pandoc -f org -t markdown -o test.md test.org or pandoc --filter pandoc-citeproc test.org -s -o test.md which reproduces the examples I showed above, but it actually failed - I think I am missing insights in how pandoc, hugo and ox-hugo actually work. Could you help? :)

ox-hugo doesn't do direct Org to Md conversion using pandoc. If the Pandoc citation feature is enabled, ox-hugo first exports the Md as usual and then it post-processing that Md to Md using pandoc. Thinking of pandoc just _sanitizing_ the markdown ox-hugo exports to markdown again but with the citations expanded.

This is where all that happens: https://github.com/kaushalmodi/ox-hugo/blob/b6f4142de2c36b37eb1b54a5005f2a43ceb65cd5/ox-hugo-pandoc-cite.el#L102-L137

**Comment by kaushalmodi** [comment] 2020-04-17 15:51
So the MWE here should be the Markdown file that ox-hugo generates.. To get that, 

1. Export using ox-hugo without the pandoc citations enabled.
2. Then pass that .md to pandoc with the switches that ox-hugo uses.

If you export an Org file/subtree with pandoc citations enables, you will see something like this in the Emacs \*Messages\* buffer:

```
[ox-hugo] Post-processing citations using Pandoc command:
  pandoc -f markdown -t markdown-citations-simple_tables+pipe_tables-raw_attribute-fenced_divs-fenced_code_attributes-bracketed_spans --atx-headers --id-prefix=fn: --bibliography=cite/bib/bib1.bib --bibliography=cite/bib/bib2.bib -o /tmp/citations-example-toml.Zmm9ao.md /home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/content/posts/citations-example-toml.md
Wrote /home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/elisp/ox-hugo/test/site/content/posts/citations-example-toml.md
```

So the key here is **pandoc -f markdown -t markdown-citations-simple_tables+pipe_tables-raw_attribute-fenced_divs-fenced_code_attributes-bracketed_spans --atx-headers --id-prefix=fn: --bibliography=cite/bib/bib1.bib --bibliography=cite/bib/bib2.bib -o PANDOC_OUTPUT.md OX_HUGO_OUTPUT.md**

**Comment by hungpham2511** [comment] 2020-06-13 03:04
Using pandoc 2.9.x with the lastest ox-hugo on master branch I have this error message:

```
org-hugo-pandoc-cite--fix-pandoc-output: Invalid use of ‘\’ in replacement text
```

**Comment by kaushalmodi** [comment] 2020-06-13 10:53
@hungpham2511 The issue is because of a regression in newer pandoc versions. Earlier pandoc used to convert file: links in Org to Markdown. How it does not. 

Can you or someone please file a bug report on pandoc repo? See my above comment on how to reproduce this issue using pandoc.

**Comment by hungpham2511** [comment] 2020-06-13 11:10
Interesting, I actually tried to use pandoc 2.5 and has the same issue with the backslash before underscores.

**Comment by kaushalmodi** [comment] 2020-06-13 11:17
> Seem like pandoc can't understand hugo's relref shortcode there.

Hmm, I am wondering why we didn't see this issue before. Maybe no one used file: links and image links with Pandoc...

**Comment by benmezger** [comment] 2020-11-14 16:44
I solved this issue on OSX by downgrading `pandoc` with  `brew switch pandoc 2.10.1`

**Comment by HaoZeke** [comment] 2021-07-27 16:41
For me this works on `2.13` but breaks on `2.14.x` again.

**Comment by kaushalmodi** [comment] 2021-07-27 16:53
@HaoZeke Can you confirm that this issue doesn't happen if you revert to pandoc 2.13?

_Note that the ox-hugo test suite was last updated to work with pandoc 2.11.4 though (https://ox-hugo.scripter.co/doc/requirements/)._

**Comment by HaoZeke** [comment] 2021-07-27 16:55
Yup @kaushalmodi, updated with build logs and outputs.

**Comment by kaushalmodi** [comment] 2021-07-27 16:59
Thanks for the updated logs. To better track this, can you open a different issue specific to this regression in pandoc 2.14?

I believe this particular issue should have been long closed (I'll close it once you create a new issue). 

Please post a test Org file and expected Markdown. I will not be able to get to fixing it right now, but it will still be good to track this regression separately.

**Comment by kaushalmodi** [comment] 2022-01-04 00:52
Reviewing this whole thread once again, it looks like the original issue was fixed in https://github.com/kaushalmodi/ox-hugo/pull/340 and we are tracking the issue with pandoc messing up the Hugo shortcodes like `relref` in https://github.com/kaushalmodi/ox-hugo/issues/455.

So I am closing this thread. Please let me know if this thread needs to be left open.

**Closed by kaushalmodi** 2022-01-04 00:52 UTC
Labels: help wanted, pandoc
