### ISSUE TITLE
[Feature question] Export logbook to timeline

### ISSUE THREAD

**Issue by RidaAyed** [kaushalmodi/ox-hugo#459] opened 2021-08-12 08:03 UTC
Any hints on how to have logbook entries exported as timeline?

https://github.com/jjuliano/org-simple-timeline

![scrnsht](https://i.imgur.com/Z3rKPD0.png)

**Comment by kaushalmodi** [comment] 2021-12-18 22:39
Closed as a duplicate of https://github.com/kaushalmodi/ox-hugo/issues/203

**Closed by kaushalmodi** 2021-12-18 22:39 UTC
Labels: wishlist
