### ISSUE TITLE
when Source blocks use -n or :hl_lines , the export md file lost Indentation

### ISSUE THREAD

**Issue by yyangdid** [kaushalmodi/ox-hugo#397] opened 2020-09-30 12:05 UTC
## Actual Behavior

when Source blocks use -n or :hl_lines , the export md file lost indentation.

## Expected Behavior

keep indentation.

## How to Reproduce the Issue

export org file.

### Example Org File

```
#+BEGIN_SRC java -n :hl_lines 1,3
 public static void main (String[] args) {
     System.our.println("HELLO WORLD!!");
 }
#+END_SRC
```

### Generated Markdown File or Error

```
{{< highlight java "linenos=table, linenostart=1, hl_lines=1 3" >}}
public static void main (String[] args) {
System.out.println("HELLO WORLD!!");
}
{{< /highlight >}}
```

`lost indentation`

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

  

</details>

**Comment by kaushalmodi** [comment] 2020-10-12 12:51
Hello, I tried out your example, but I cannot reproduce the issue.

Below, the snippet in the top window is your example, and the code in the bottom window is the Markdown exported by ox-hugo -- The indentation is intact in that.

![image](https://user-images.githubusercontent.com/3578197/95748481-0d0cb200-0c68-11eb-918d-4df4428098be.png)

Do you have some function adding to a hook in your emacs config that might be stripping off that indentation, or may be a something in your Org setup? 

Can you try to comment out all your Org mode customizations, so that Org and ox-hugo runs with the default setup?

**Comment by kaushalmodi** [comment] 2020-10-12 12:53
@yyangdid This seems related: https://github.com/kaushalmodi/ox-hugo/issues/314#issuecomment-582875230

Can you remove any customization of `org-src-preserve-indentation` and see if that fixes this problem?

**Comment by yyangdid** [comment] 2020-10-16 13:22
I found something about `format-all` package . 

this is my format-all config:
``` lisp
(use-package format-all
  :ensure t
  :init
	(add-hook 'before-save-hook 'format-all-buffer)
  )
```
Don't use `format-all` package , everything is ok .

**Comment by kaushalmodi** [comment] 2020-10-16 14:46
Awesome! So I can close this issue? See if you can tweak that package to not modify Org and Markdown files.

**Comment by yyangdid** [comment] 2020-10-17 01:53
Yes, close, thank you . 👍

**Closed** 2020-10-17 02:01 UTC
