### ISSUE TITLE
ERROR export artile when hugo_draft is "true"

### ISSUE THREAD

**Issue by shuxiao9058** [kaushalmodi/ox-hugo#153] opened 2018-04-11 12:35 UTC
It occurs an error as below
```
Debugger entered--Lisp error: (wrong-type-argument overlayp nil)
  overlay-start(nil)
  whitespace-point--flush-used(1398)
  font-lock-fontify-keywords-region(1397 1398 nil)
  font-lock-default-fontify-region(1397 1398 nil)
  #[(reg) "\211G\306U\203	\211A\242\202\307\310\311	GD\"	\211A\242	@\nb\210\312
\f\"\210\313
=?\2054
\"\210\214\314\311\211\f\203Q
>\204Q\n}\210\n\311#\210,\315\",\207" [reg --cl-rest-- beg end ovl mode 3 signal wrong-number-of-arguments nil mmm-set-current-pair mmm-set-local-variables t mmm-save-changed-local-variables mmm-previous-submode mmm-current-overlay syntax-ppss-cache syntax-ppss-last font-lock-dont-widen mmm-c-derived-modes func mmm-current-submode] 5]((1397 1398 nil))
  mapc(#[(reg) "\211G\306U\203	\211A\242\202\307\310\311	GD\"	\211A\242	@\nb\210\312
\f\"\210\313
=?\2054
\"\210\214\314\311\211\f\203Q
>\204Q\n}\210\n\311#\210,\315\",\207" [reg --cl-rest-- beg end ovl mode 3 signal wrong-number-of-arguments nil mmm-set-current-pair mmm-set-local-variables t mmm-save-changed-local-variables mmm-previous-submode mmm-current-overlay syntax-ppss-cache syntax-ppss-last font-lock-dont-widen mmm-c-derived-modes func mmm-current-submode] 5] ((1397 1398 nil)))
  mmm-fontify-region-list(markdown-mode ((1397 1398 nil)))
  #[(elt) "@\301N\205
\302@A\"\207" [elt mmm-font-lock-mode mmm-fontify-region-list] 3]((markdown-mode (1397 1398 nil)))
  mapc(#[(elt) "@\301N\205
\302@A\"\207" [elt mmm-font-lock-mode mmm-fontify-region-list] 3] ((markdown-mode (1397 1398 nil))))
  mmm-fontify-region(1397 1398 nil)
  font-lock-fontify-region(1397 1398)
  font-lock-after-change-function(1397 1398 0)
  basic-save-buffer(nil)
  save-buffer()
  write-file("/Users/xx/workspace/blogs/hugo/content/writing-hugo-blog-in-org-file-export.md")
  org-export-to-file(hugo "/Users/xx/workspace/blogs/hugo/content/writing-hugo-blog-in-org-file-export.md" nil nil nil)
  org-hugo-export-to-md(nil nil nil)
  (org-open-file (org-hugo-export-to-md nil s v))
  (if a (org-hugo-export-to-md t s v) (org-open-file (org-hugo-export-to-md nil s v)))
  (lambda (a s v _b) (if a (org-hugo-export-to-md t s v) (org-open-file (org-hugo-export-to-md nil s v))))(nil nil nil nil)
  org-export-dispatch(nil)
  funcall-interactively(org-export-dispatch nil)
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)
```

**Comment by shuxiao9058** [comment] 2018-04-11 12:38
[debug.txt](https://github.com/kaushalmodi/ox-hugo/files/1898782/debug.txt)

[writing-hugo-blog-in-org-file-export.txt](https://github.com/kaushalmodi/ox-hugo/files/1898785/writing-hugo-blog-in-org-file-export.txt)

**Comment by kaushalmodi** [comment] 2018-04-11 12:44
It looks like an `mmm` mode is causing the issue.. the relevant part of your backtrace is:

```
Debugger entered--Lisp error: (wrong-type-argument overlayp nil)
  overlay-start(nil)
  whitespace-point--flush-used(1398)
  font-lock-fontify-keywords-region(1397 1398 nil)
  font-lock-default-fontify-region(1397 1398 nil)
  #[(reg) "�\211�G\306U\203��	\211A�\242\202��\307\310\311	GD\"�	\211A�\242�	@�\nb\210\312
\f\"\210\313��
=?\2054�
��\"\210\214\314\311\211������\f\203Q�
��>\204Q�\n�}\210��\n�\311#\210,\315����\",\207" [reg --cl-rest-- beg end ovl mode 3 signal wrong-number-of-arguments nil mmm-set-current-pair mmm-set-local-variables t mmm-save-changed-local-variables mmm-previous-submode mmm-current-overlay syntax-ppss-cache syntax-ppss-last font-lock-dont-widen mmm-c-derived-modes func mmm-current-submode] 5]((1397 1398 nil))
  mapc(#[(reg) "�\211�G\306U\203��	\211A�\242\202��\307\310\311	GD\"�	\211A�\242�	@�\nb\210\312
\f\"\210\313��
=?\2054�
��\"\210\214\314\311\211������\f\203Q�
��>\204Q�\n�}\210��\n�\311#\210,\315����\",\207" [reg --cl-rest-- beg end ovl mode 3 signal wrong-number-of-arguments nil mmm-set-current-pair mmm-set-local-variables t mmm-save-changed-local-variables mmm-previous-submode mmm-current-overlay syntax-ppss-cache syntax-ppss-last font-lock-dont-widen mmm-c-derived-modes func mmm-current-submode] 5] ((1397 1398 nil)))
  mmm-fontify-region-list(markdown-mode ((1397 1398 nil)))
  #[(elt) "�@\301N\205
�\302�@�A\"\207" [elt mmm-font-lock-mode mmm-fontify-region-list] 3]((markdown-mode (1397 1398 nil)))
  mapc(#[(elt) "�@\301N\205
�\302�@�A\"\207" [elt mmm-font-lock-mode mmm-fontify-region-list] 3] ((markdown-mode (1397 1398 nil))))
  mmm-fontify-region(1397 1398 nil)
  font-lock-fontify-region(1397 1398)
  font-lock-after-change-function(1397 1398 0)
  basic-save-buffer(nil)
  save-buffer()
  write-file("/Users/xx/workspace/blogs/hugo/content/writing-hugo-blog-in-org-file-export.md")
  org-export-to-file(hugo "/Users/xx/workspace/blogs/hugo/content/writing-hugo-blog-in-org-file-export.md" nil nil nil)
org-hugo-export-to-md(nil nil nil)
```

So it is read as:

org-hugo-export-to-md (this is the last command called out of ox-hugo) -> org-export-to-file (from ox.el i.e. Org core) -> write-file -> save-buffer -> basic-save-buffer -> font-lock-\* -> **mmm-\***

**Comment by kaushalmodi** [comment] 2018-04-11 12:45
As you see the error occurs in one of the `mmm-*` functions.

Do you want to disable the package calling those `mmm-*` functions and retry the export?

**Comment by shuxiao9058** [comment] 2018-04-11 12:47
But it is fine when hugo_draft is false.I am use spacemacs, perhaps the mmm is the core packgae in spacemacs.

**Comment by kaushalmodi** [comment] 2018-04-11 12:49
Also I see that you are using one of the test files: [`writing-hugo-blog-in-org-file-export.org`][1].

That definitely works because it exports to [this Markdown][2] and then to [this HTML][3] using Hugo.

[1]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content-org/writing-hugo-blog-in-org-file-export.org
[2]: https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/writing-hugo-blog-in-org-file-export.md
[3]: https://ox-hugo.scripter.co/test/writing-hugo-blog-in-org-file-export/

**Comment by kaushalmodi** [comment] 2018-04-11 12:53
I see that after `font-lock-fontify-region` runs, `mmm-fontify-region` is called.. so I have to guess that `mmm-fontify-region` advices `font-lock-fontify-region`.. Do `C-h f font-lock-fontify-region` and see if you get any clue.. if it is advised, remove that advise. 

In parallel, also file a bug report for the mmm package as they would be able to understand/debug this debug backtrace and fix the bug.

**Comment by shuxiao9058** [comment] 2018-04-11 12:54
ok, let me have a try, thanks for your reply.

**Comment by shuxiao9058** [comment] 2018-04-11 12:59
It works fine when disable the markdown layer in spacemacs, so this is a bug with mmm, you  are right.Than you very much!!!

**Comment by dgutov** [comment] 2018-04-11 15:41
Could you guys try this patch to `mmm-mode`?

```diff
diff --git a/mmm-vars.el b/mmm-vars.el
index 3c14b09..9abf554 100644
--- a/mmm-vars.el
+++ b/mmm-vars.el
@@ -311,6 +311,8 @@
     (whitespace-font-lock-mode buffer)
     (whitespace-font-lock-keywords buffer)
     (whitespace-mode buffer)
+    (whitespace-point--used buffer)
+    (whitespace-point buffer)
     forward-sexp-function
     smie-rules-function
     smie-grammar
```

**Comment by kaushalmodi** [comment] 2018-04-11 20:06
Thanks @dgutov. I'll wait for @shuxiao9058 to try this out as I don't have `mmm-mode` installed, and also don't know how he configured `mmm-mode` + `markdown-mode` + ??.

**Comment by shuxiao9058** [comment] 2018-04-12 02:34
@kaushalmodi Hi, I have use the default markdown layer(with mmm-mode) in spacemacs. 

@dgutov It always error with this patch.

Here is the backtrace with this patch [backtrace.txt](https://github.com/kaushalmodi/ox-hugo/files/1901131/backtrace.txt).

I'm sorry that I am not familiar with elisp.

**Comment by shuxiao9058** [comment] 2018-04-12 02:46
It produce an error when open the result md file.

Wrote /Users/xxx/workspace/blogs/hugo/content/writing-hugo-blog-in-org-file-export.md
Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument markerp nil)
Error during redisplay: (jit-lock-function 501) signaled (wrong-type-argument number-or-marker-p nil)
Error during redisplay: (jit-lock-function 1001) signaled (wrong-type-argument number-or-marker-p nil)
font-lock-fontify-keywords-region: Wrong type argument: markerp, nil [5 times]

[writing-hugo-blog-in-org-file-export.md.txt](https://github.com/kaushalmodi/ox-hugo/files/1901154/writing-hugo-blog-in-org-file-export.md.txt)

**Comment by dgutov** [comment] 2018-04-12 06:00
OK, how about this one?

```diff
diff --git a/mmm-vars.el b/mmm-vars.el
index 3c14b09..bd63da6 100644
--- a/mmm-vars.el
+++ b/mmm-vars.el
@@ -311,6 +311,9 @@
     (whitespace-font-lock-mode buffer)
     (whitespace-font-lock-keywords buffer)
     (whitespace-mode buffer)
+    (whitespace-point--used buffer)
+    (whitespace-point buffer)
+    (whitespace-bob-marker buffer)
     forward-sexp-function
     smie-rules-function
     smie-grammar
```

**Comment by shuxiao9058** [comment] 2018-04-12 07:27
Also error, but the line number is not 311, is 314. The source code of mmm is not the same?
![image](https://user-images.githubusercontent.com/3312525/38662133-e0401424-3e65-11e8-9c13-7d005918c472.png)

**Comment by dgutov** [comment] 2018-04-13 12:30
> Also error, but the line number is not 311, is 314. The source code of mmm is not the same?

That's just the diff format. Line number of the first mentioned line, not the first changed line.

If the error is still there, I'm out of guesses for now. Maybe I'll find some time next week to try and reproduce the issue on my machine.

**Comment by dgutov** [comment] 2018-04-13 12:31
In the meantime, try disabling `whitespace-mode` in these buffers.

**Comment by kaushalmodi** [comment] 2018-08-10 18:29
Closing this issue here as it's not related to `ox-hugo` and is being tracked at https://github.com/purcell/mmm-mode/issues/85. @shuxiao9058 Please follow up in the linked `mmm-mode` issue.

**Closed by kaushalmodi** 2018-08-10 18:29 UTC
Labels: bug, upstream
