### ISSUE TITLE
Table of content with extra empty div

### ISSUE THREAD

**Issue by finex** [kaushalmodi/ox-hugo#362] opened 2020-05-16 19:06 UTC
## Actual Behavior
The `ox-hugo-toc` div element contains an empty `<div></div>` before the heading element.

## Expected Behavior
There shouldn't be an empty div.

## How to Reproduce the Issue
Create a simple .org file with a TOC and export using ox-hugo.

### Example Org File
```
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: /
#+EXPORT_FILE_NAME: privacy.md

#+OPTIONS: toc:2
#+LANGUAGE: it

#+TITLE: Privacy Policy
#+HUGO_CUSTOM_FRONT_MATTER: :type "page"
#+HUGO_CUSTOM_FRONT_MATTER: :robotsdisallow false
```

### Generated Markdown File or Error
Relevant part of Markdown generated file:
```
<div class="ox-hugo-toc toc">
<div></div>

<div class="heading">Indice</div>
```

## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
     of 2019-08-29

## Org Version

    Org mode version 9.4 (nil @ /home/username/.emacs.d/.local/straight/build/org-mode/)

## Hugo Version

    Hugo Static Site Generator v0.70.0/extended linux/amd64 BuildDate: unknown

### Org `load-path` shadows

**Warning**: Possible mixed installation of Org

    /home/username/.emacs.d/.local/straight/build/org-journal/org-journal hides /home/username/.emacs.d/.local/elpa/org-journal-20200103.1227/org-journal
    /home/username/.emacs.d/.local/straight/build/org-journal/org-journal-autoloads hides /home/username/.emacs.d/.local/elpa/org-journal-20200103.1227/org-journal-autoloads
    /home/username/.emacs.d/.local/straight/build/ox-hugo/org-hugo-auto-export-mode hides /home/username/.emacs.d/.local/elpa/ox-hugo-20190905.303/org-hugo-auto-export-mode

Study the output of `M-x list-load-path-shadows`.

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-section</td>
<td class="org-left">&ldquo;posts&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-tag-processing-functions</td>
<td class="org-left">(org-hugo&#x2013;tag-processing-fn-replace-with-spaces-maybe org-hugo&#x2013;tag-processing-fn-replace-with-hyphens-maybe)</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">&ldquo;ox-hugo&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">(&ldquo;jpg&rdquo; &ldquo;jpeg&rdquo; &ldquo;tiff&rdquo; &ldquo;png&rdquo; &ldquo;svg&rdquo; &ldquo;gif&rdquo; &ldquo;mp4&rdquo; &ldquo;pdf&rdquo; &ldquo;odt&rdquo; &ldquo;doc&rdquo; &ldquo;ppt&rdquo; &ldquo;xls&rdquo; &ldquo;docx&rdquo; &ldquo;pptx&rdquo; &ldquo;xlsx&rdquo;)</td>
</tr>

<tr>
<td class="org-left">org-hugo-date-format</td>
<td class="org-left">&ldquo;%Y-%m-%dT%T%z&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-paired-shortcodes</td>
<td class="org-left">&ldquo;&rdquo;</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-suppress-lastmod-period</td>
<td class="org-left">0.0</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">&ldquo;toml&rdquo;</td>
</tr>
</tbody>
</table>

</details>

**Comment by kaushalmodi** [comment] 2020-05-16 22:35
The empty divs are intentional -- they are a hack added for Blackfriday, but they don't hurt the GoldMark parsing. 

I plan to clean this up.. seen the last pinned issue.

**Comment by finex** [comment] 2020-05-17 07:06
Hi, ok, thanks for the info :+1:

**Comment by kaushalmodi** [comment] 2020-05-17 15:09
Closing this as this is a duplicate of https://github.com/kaushalmodi/ox-hugo/issues/306 .

From my experience, the extra divs are just an eye sore and don't affect the functionality. But they will be taken care of once the Goldmark/Commonmark exporter is separated from the Blackfriday exporter.

**Closed by kaushalmodi** 2020-05-17 15:09 UTC
