### ISSUE TITLE
tags_weight is not rendering in front matter correctly

### ISSUE THREAD

**Issue by tabroughton** [kaushalmodi/ox-hugo#335] opened 2020-03-05 12:49 UTC
using a single org file, subtree export is not rendering tags_weight [as described in the docs](https://ox-hugo.scripter.co/doc/org-meta-data-to-hugo-front-matter/).

## Actual Behavior

Output using the same property example as in the docs `:EXPORT_HUGO_WEIGHT: :tags 123` results in `weight = ":tags 123`

## Expected Behavior

output should be `tags_weight = 123`

## How to Reproduce the Issue

export a subtree 

### Example Org File
```
** This City   :technology:
    :PROPERTIES:
    :EXPORT_DATE: [2020-03-04 Wed 19:31]
    :EXPORT_FILE_NAME: how-I-built-this-city
    :EXPORT_HUGO_WEIGHT: :tags 123
    :END:
 I built this city from rock 'n' roll
```
### Generated Markdown File or Error
```
+++
title = "This City"
date = 2020-03-04T19:31:00+00:00
tags = ["technology"]
weight = ":tags 123"
draft = false
+++

I built this city from rock 'n' roll
```
## Ox-Hugo Debug Information

<details>
  <summary>Debug Info</summary>

# Debug information for `ox-hugo`

## Emacs Version

    GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
     of 2019-08-29

## Org Version

    Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/share/emacs/26.3/lisp/org/)

## Hugo Version

    Hugo Static Site Generator v0.65.3 linux/amd64 BuildDate: 2020-02-23T15:14:25Z

### Org `load-path` shadows

No Org mode shadows found in `load-path`

## `ox-hugo` defcustoms

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">org-hugo-default-section-directory</td>
<td class="org-left">"posts"</td>
</tr>

<tr>
<td class="org-left">org-hugo-use-code-for-kbd</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-preserve-filling</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-delete-trailing-ws</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-prefer-hyphen-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-allow-spaces-in-tags</td>
<td class="org-left">t</td>
</tr>

<tr>
<td class="org-left">org-hugo-auto-set-lastmod</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-toc</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-export-with-section-numbers</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>

<tr>
<td class="org-left">org-hugo-default-static-subdirectory-for-externals</td>
<td class="org-left">"ox-hugo"</td>
</tr>

<tr>
<td class="org-left">org-hugo-external-file-extensions-allowed-for-copying</td>
<td class="org-left">("jpg" "jpeg" "tiff" "png" "svg" "pdf" "odt")</td>
</tr>

<tr>
<td class="org-left">org-hugo-langs-no-descr-in-code-fences</td>
<td class="org-left">nil</td>
</tr>

<tr>
<td class="org-left">org-hugo-front-matter-format</td>
<td class="org-left">"toml"</td>
</tr>
</tbody>
</table>

  

</details>

**Comment by kaushalmodi** [comment] 2020-03-05 13:51
Hello,

I am unable to reproduce the outcome you are seeing.

With this Org content:

```org
* Issues                                                            :@issues:
:PROPERTIES:
:EXPORT_HUGO_SECTION: issues
:END:
** Issue 335                                                :taxonomy_weight:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: 335
:EXPORT_HUGO_WEIGHT: :tags 123
:EXPORT_FILE_NAME: index
:END:
#+begin_description
Test the exporting of taxonomy weight parameters like ~tags_weight~.
#+end_description
```

I get:

```md
+++
title = "Issue 335"
description = "Test the exporting of taxonomy weight parameters like `tags_weight`."
tags = ["taxonomy-weight"]
categories = ["issues"]
draft = false
tags_weight = 123
+++
```

**Comment by kaushalmodi** [comment] 2020-03-05 14:29
I have committed this to the test suite now:

- https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/test/site/content/issues/335/index.md
- https://ox-hugo.scripter.co/test/issues/335/

Can you check your emacs config if you are advising some org or org-babel functions?

**Comment by tabroughton** [comment] 2020-03-06 09:11
I tried your example but I got this output:

```
+++
title = "Issue 335"
tags = ["taxonomy-weight"]
categories = ["issues"]
weight = ":tags 123"
draft = false
+++

<div class="description">
<div></div>

Test the exporting of taxonomy weight parameters like `tags_weight`.

</div>
```
I've pasted in my org configs from my init.el as I wasn't sure what you were asking about with org or org-babel functions.  Sorry it's a bit messy but do you think there's anything in there that would cause problems?

```
;;------- configure org mode
(use-package org
  :config
  ;; some org mode configs
  (setq org-todo-keywords
	'((sequence "TODO(t)" "WIP(w!)" "BLOCKED(b@/!)" "REVIEW(r@/!)" "|" "DONE(d!)")))

  (setq org-todo-keyword-faces
	'(("WIP" . (:foreground "orange" :weight bold))
	  ("REVIEW" . (:foreground "yellow" :weight bold))))

  ;; let's set the default logging into a draw and use LOGBOOK (defined with t)
  (setq org-log-into-drawer t)
  (setq org-log-done 'time)
  ;;highlight source code blocks in org
  (setq org-src-fontify-natively t)

  ;; remap M-tab (os switch app) to M-* (M-S-8) - this will help with completions etc
  (global-set-key (kbd "M-*") (kbd "M-TAB"))
  
  ;; set up for org capture
  (with-eval-after-load 'org 
    (custom-set-variables
     '(org-directory "~/Documents/org")
     '(org-agenda-files (list org-directory)))
    (setq org-default-notes-file (concat org-directory "/notes.org"))
    (setq org-capture-templates
	  '(("j" "Counselling Journal" entry (file+olp+datetree "~/Documents/counselling-skills/journal.org")
	     "**** TODO Week %?\n(Entered on %^{entered_on}U)\n\n" :time-prompt u)
	    ("u" "Counselling Journal Update" entry (file+olp+datetree "~/Documents/counselling-skills/journal.org")
	     "***** TODO %?\n(Entered on %^{entered_on}U)\n\n" :time-prompt u)
	    ("h" "Counselling Homework" checkitem (file+olp+datetree "~/Documents/counselling-skills/homework.org")
             "[ ] %? (Assigned on %^{assigned_on}U)" :time-prompt u :prepend 1))))
  (global-set-key (kbd "\C-cc") 'org-capture)

  ;; allow empasis to span multiple lines, needed for auto-fill-mode
  ;; see https://emacs.stackexchange.com/questions/13820/inline-verbatim-and-code-with-quotes-in-org-mode/13828#13828
  ;; we'll allow it across 6 lines for now but if I get an issue I know where to look
  (with-eval-after-load 'org
    (org-set-emph-re 'org-emphasis-regexp-components org-emphasis-regexp-components)
    (setcar (nthcdr 4 org-emphasis-regexp-components) 6))
	:init
	(add-hook 'org-mode-hook 'auto-fill-mode)
	(add-hook 'org-mode-hook 'flyspell-mode)
 )

;; keybinding to add notes section for reveal js hugo markdown
(defun reveal-insert-notes ()
  "Insert notes shortcode for hugo reveal"
  (interactive)
  (insert "\n{{% note %}}\n  \n{{% /note %}}\n")
  (backward-to-indentation 2))
(global-set-key (kbd "C-M-n") 'reveal-insert-notes)

;;let's use org with hugo!
(use-package ox-hugo
  :ensure t
  :after ox)

```

**Comment by kaushalmodi** [comment] 2020-03-06 12:49
Hmm, something's definitely not right. You probably have multiple versions of ox-hugo installed. Did you install from Melpa "stable" at any point? I'd recommend that you delete all versions of ox-hugo on your machine and reinstall using regular Melpa.

**Comment by kaushalmodi** [comment] 2020-03-06 12:54
Make sure that your package-archives is set to "melpa" as explained here: http://melpa.org/#/getting-started

**Comment by tabroughton** [comment] 2020-03-06 15:11
Yes, I was using melpa-stable, it was installing ox-hugo-0.8 - I've removed that, added the recommended melpa archive and reinstalled.  My output now works as expected.

```
+++
title = "Issue 335"
description = "Test the exporting of taxonomy weight parameters like `tags_weight`."
tags = ["taxonomy-weight"]
categories = ["issues"]
draft = false
tags_weight = 123
+++
```

thanks  for quick troubleshooting - really great package btw

**Closed** 2020-03-06 15:11 UTC
